name: custom_refresh_indicator
description: Widget that makes it easy to implement a custom pull to refresh gesture.
version: 4.0.1
repository: https://github.com/gonuit/flutter-custom-refresh-indicator
issue_tracker: https://github.com/gonuit/flutter-custom-refresh-indicator/issues
homepage: https://github.com/gonuit/flutter-custom-refresh-indicator

scripts:
  format: dart format . --line-length=120

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  rps: ^0.7.0

flutter:

funding:
- https://www.paypal.com/donate/?hosted_button_id=Z82R98MAR4URE
- https://www.buymeacoffee.com/kamilklyta

topics:
 - widgets
 - animation
 - pull-to-refresh
 - refresh-indicator
 - p2r

screenshots:
  - description: The custom refresh indicator package thumbnail.
    path: screenshots/thumbnail.png
